### ISSUE TITLE
Add Increase/Decrease allowance to prevent sandwich attacks

### ISSUE THREAD

**Issue by davidtai** [casper-ecosystem/cep18#59]
This note from our security audit was never pushed back to the casper labs erc20
https://github.com/Rengo-Labs/CasperLabs-Crates/blob/6e2e449d11c097df318e6660667dc85c8bc12aae/casper_erc20_new/src/lib.rs#L207
https://github.com/Rengo-Labs/CasperLabs-Crates/blob/6e2e449d11c097df318e6660667dc85c8bc12aae/casper_erc20_new/src/lib.rs#L223

Per QSP-7
https://certificate.quantstamp.com/full/rengo-labs

**Comment by RitaMAllenCA** [comment]
spoke with David Tai about the sandwich attack thingy
turns out it's "just" a double spend attack their resolution is breaking the API, so no immidiate solution from me, but will be addressed in the "rework"
