### ISSUE TITLE
[client-js] Add CI scripts for testing

### ISSUE THREAD

**Issue by hoffmannjan** [casper-ecosystem/cep18#66]
you can most likely reuse script from there
https://github.com/casper-ecosystem/cep-78-enhanced-nft/blob/dev/.github/workflows/ci-cep-78-client.yml

**Comment by gyroflaw** [comment]
fixed in https://github.com/casper-ecosystem/cep18/pull/69

**Comment by hoffmannjan** [comment]
fixed in https://github.com/casper-ecosystem/cep18/pull/69
