### ISSUE TITLE
Add client support for decrease_allowance

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-ecosystem/cep18#71]
This was added to address an issue reported by the community https://github.com/casper-ecosystem/cep18/blob/i335/cep18/src/main.rs#L96

**Comment by RitaMAllenCA** [comment]
@hoffmannjan @gyroflaw please consider these the priority for the sprint, thanks.

**Comment by gyroflaw** [comment]
let me handle this @RitaMAllenCA

**Comment by gyroflaw** [comment]
fixed in https://github.com/casper-ecosystem/cep18/pull/69

**Comment by hoffmannjan** [comment]
as @gyroflaw said its done
