### ISSUE TITLE
update client for events_mode option

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-ecosystem/cep18#73]
https://github.com/casper-ecosystem/cep18/blob/i335/cep18/src/main.rs#L113

**Comment by RitaMAllenCA** [comment]
@hoffmannjan @gyroflaw final new priority

**Comment by gyroflaw** [comment]
fixed in https://github.com/casper-ecosystem/cep18/pull/69

**Comment by hoffmannjan** [comment]
fixed in https://github.com/casper-ecosystem/cep18/pull/69

**Comment by RitaMAllenCA** [comment]
reopening this since there are events that still need to be supported in the SDK.   @deuszex @gyroflaw please let me know when you confirm we have the missing events.....

**Comment by RitaMAllenCA** [comment]
@hoffmannjan see above
